export const API_DATE_FORMAT = 'DD MMMM YYYY';
export const API_LAST_UPDATED_DATE_FORMAT = 'MM/DD/YYYY HH:mm:ss A Z';
export const DISPLAY_DATE_FORMAT = 'DD MMMM YYYY';
export const API_REQUEST_DATE_FORMAT = 'YYYY-MM-DD';
